//! Apple Neural Engine (ANE) Integration Module
//!
//! Safe Rust bindings to Apple's Neural Engine for efficient deep learning inference and training.
//!
//! # Overview
//!
//! The ANE module provides a complete abstraction over Apple's private ANE framework via `objc2`
//! Rust bindings. It enables high-performance neural network computation on Apple Silicon devices
//! (M1/M2/M3/M4 chips).
//!
//! # Architecture
//!
//! The module is organized into five core components:
//!
//! - **Error Handling** (`error.rs`): Comprehensive error types for all ANE operations
//! - **Runtime** (`runtime.rs`): Framework loading and MIL compilation interface
//! - **Kernel** (`kernel.rs`): ANEKernel lifecycle management with I/O operations
//! - **IOSurface** (`io_surface.rs`): RAII-safe memory management for data transfer
//! - **Weight Blobs** (`weight_blob.rs`): Weight format abstraction (FP32, FP16, quantized int8)
//!
//! # Design Philosophy
//!
//! **CPU-ANE Coordination**: The module follows a CPU ↔ ANE split design:
//! - Heavy compute (forward/backward passes) → ANE
//! - Data coordination, loading, optimization → CPU
//! - This balance maximizes ANE utilization while keeping the system flexible
//!
//! **Type Safety**: All operations use Rust's type system to prevent:
//! - Shape mismatches (tensor dimensions validated at compile/runtime)
//! - Memory safety (RAII patterns, no manual cleanup)
//! - Silent failures (Result<T> throughout)
//!
//! **Numerical Stability**: ANE operations use:
//! - Per-row quantization with scale tracking
//! - Epsilon guards for division by zero
//! - Numerically stable softmax (max subtraction)
//!
//! # Key Components
//!
//! ## ANEError
//!
//! Comprehensive error enum covering all failure modes:
//! - Framework not found
//! - Compilation failures
//! - Evaluation failures
//! - I/O Surface errors
//! - Shape mismatches
//! - Configuration errors
//!
//! ## ANERuntime & Compilation
//!
//! Loads the private ANE framework and compiles MIL code to ANE kernels:
//! ```ignore
//! let request = ANECompileRequest {
//!     mil_text: "func matmul...".to_string(),
//!     weights: HashMap::new(),
//!     input_sizes: vec![4096],
//!     output_sizes: vec![1024],
//! };
//! let kernel = request.compile()?;
//! ```
//!
//! ## ANEKernel Lifecycle
//!
//! Manages kernel execution with safe I/O:
//! ```ignore
//! let mut kernel = ANECompileRequest::compile()?;
//! kernel.write_input(0, &input_data)?;
//! kernel.eval()?;
//! let output = kernel.read_output(0)?;
//! ```
//!
//! ## IOSurface Wrapper
//!
//! RAII-safe memory management for ANE data transfer:
//! ```ignore
//! let mut surface = IOSurface::new(buffer_size)?;
//! surface.write(&data)?;
//! let result = surface.read()?;
//! // Automatically cleaned up when dropped
//! ```
//!
//! ## Weight Blob Builders
//!
//! Format abstraction for multiple weight precisions:
//! ```ignore
//! // FP32 format
//! let blob_fp32 = WeightBlob::from_f32(&weights, rows, cols);
//!
//! // Quantized int8 with scale
//! let (blob_int8, scales) = WeightBlob::quantize_f32(&weights, rows, cols);
//! ```
//!
//! # Integration with TransformerANE
//!
//! The ANE module integrates with the training system:
//! 1. MIL code generated by layers/mil_gen.rs
//! 2. Weights converted to appropriate format via WeightBlob
//! 3. Kernel compiled via ANERuntime
//! 4. Forward/backward passes executed via ANEKernel
//! 5. Gradients transferred back to CPU for optimization
//!
//! # Platform Requirements
//!
//! - **OS**: macOS 15+ (Sequoia)
//! - **Hardware**: Apple Silicon with ANE (M1/M2/M3/M4)
//! - **Rust**: 1.70+ with 2021 edition
//!
//! # Limitations & Future Work
//!
//! Current Phase 2 implementation:
//! - MIL code generation for attention and FFN forward passes
//! - CPU-based backward passes with cached activations
//! - Numerical gradient validation
//!
//! Phase 3 will add:
//! - Full ANE backward passes for all layers
//! - Advanced optimization (gradient accumulation on ANE, quantized training)
//! - Production checkpointing and experiment tracking

/// ANE-specific error types.
pub mod error;
pub(crate) mod blobs;
/// Low-level runtime and compile/load/eval support for the private ANE APIs.
pub mod runtime;
pub(crate) mod sys;
/// IOSurface RAII wrapper for ANE I/O operations.
pub mod io_surface;
/// Weight blob builders for ANE-compatible formats.
pub mod weight_blob;
/// ANE kernel wrapper for managing compiled models and I/O operations.
pub mod kernel;

pub use error::ANEError;
pub use io_surface::IOSurface;
pub use runtime::ANECompileRequest;
pub use weight_blob::WeightBlob;
pub use kernel::ANEKernel;

/// Result type for ANE operations
pub type Result<T> = std::result::Result<T, ANEError>;
